// <auto-generated />
namespace PassionProject_N01329988.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class candyy2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candyy2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002171822435_candyy2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
